export const ErrorCategory = {
  AUTH: "AUTH_",
  PERMISSION: "PERMISSION_",
  ACCOUNT: "ACCOUNT_",
  BROKER: "BROKER_",
  MARKET: "MARKET_",
  ORDER: "ORDER_",
  POSITION: "POSITION_",
  RISK: "RISK_",
  STRATEGY: "STRATEGY_",
  COPIER: "COPIER_",
  AUTOMATION: "AUTOMATION_",
  VALIDATION: "VALIDATION_",
  SYSTEM: "SYSTEM_",
} as const;

export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_2FA_REQUIRED: "AUTH_2FA_REQUIRED",
  AUTH_2FA_INVALID: "AUTH_2FA_INVALID",
  AUTH_TRADING_PIN_REQUIRED: "AUTH_TRADING_PIN_REQUIRED",
  AUTH_TRADING_PIN_INVALID: "AUTH_TRADING_PIN_INVALID",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_BRUTE_FORCE_LOCKED: "AUTH_BRUTE_FORCE_LOCKED",

  PERMISSION_DENIED: "PERMISSION_DENIED",
  PERMISSION_ROLE_INSUFFICIENT: "PERMISSION_ROLE_INSUFFICIENT",

  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_DISCONNECTED: "ACCOUNT_DISCONNECTED",
  ACCOUNT_LIVE_NOT_ENABLED: "ACCOUNT_LIVE_NOT_ENABLED",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

  BROKER_CONNECTION_FAILED: "BROKER_CONNECTION_FAILED",
  BROKER_UNHEALTHY: "BROKER_UNHEALTHY",
  BROKER_ORDER_REJECTED: "BROKER_ORDER_REJECTED",
  BROKER_TIMEOUT: "BROKER_TIMEOUT",

  MARKET_CLOSED: "MARKET_CLOSED",
  MARKET_SYMBOL_NOT_FOUND: "MARKET_SYMBOL_NOT_FOUND",
  MARKET_DATA_STALE: "MARKET_DATA_STALE",

  ORDER_VALIDATION_FAILED: "ORDER_VALIDATION_FAILED",
  ORDER_INSUFFICIENT_MARGIN: "ORDER_INSUFFICIENT_MARGIN",
  ORDER_DUPLICATE_REQUEST: "ORDER_DUPLICATE_REQUEST",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_INVALID_VOLUME: "ORDER_INVALID_VOLUME",
  ORDER_INVALID_PRICE: "ORDER_INVALID_PRICE",
  ORDER_REJECTED: "ORDER_REJECTED",

  POSITION_NOT_FOUND: "POSITION_NOT_FOUND",
  POSITION_ALREADY_CLOSING: "POSITION_ALREADY_CLOSING",
  POSITION_INVALID_SL: "POSITION_INVALID_SL",
  POSITION_INVALID_TP: "POSITION_INVALID_TP",
  POSITION_PARTIAL_CLOSE_INVALID: "POSITION_PARTIAL_CLOSE_INVALID",

  RISK_DAILY_LIMIT_EXCEEDED: "RISK_DAILY_LIMIT_EXCEEDED",
  RISK_DRAWDOWN_EXCEEDED: "RISK_DRAWDOWN_EXCEEDED",
  RISK_MAX_TRADES_EXCEEDED: "RISK_MAX_TRADES_EXCEEDED",
  RISK_CORRELATION_EXCEEDED: "RISK_CORRELATION_EXCEEDED",
  RISK_HARD_LIMIT_BREACHED: "RISK_HARD_LIMIT_BREACHED",
  RISK_SOFT_WARNING: "RISK_SOFT_WARNING",

  STRATEGY_INVALID: "STRATEGY_INVALID",
  STRATEGY_NOT_RUNNING: "STRATEGY_NOT_RUNNING",
  STRATEGY_ERROR: "STRATEGY_ERROR",

  COPIER_NOT_RUNNING: "COPIER_NOT_RUNNING",
  COPIER_LOOP_DETECTED: "COPIER_LOOP_DETECTED",
  COPIER_FOLLOWER_FAILED: "COPIER_FOLLOWER_FAILED",

  AUTOMATION_FAILED: "AUTOMATION_FAILED",
  AUTOMATION_COOLDOWN: "AUTOMATION_COOLDOWN",

  VALIDATION_FAILED: "VALIDATION_FAILED",
  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_RATE_LIMITED: "SYSTEM_RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorBody {
  code: ErrorCode | string;
  message: string;
  details: Record<string, unknown>;
  correlationId: string;
  timestamp: string;
}
